name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python version
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' # Replace '3.x' with the specific Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'my-flask-app' # Replace with your Azure Web App name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
