name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python version
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.0'  # Be specific with the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust path if needed

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'my-flask-app' 
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} 
        package: '.'  # Consider using RunFromPackage for efficiency
